export const CURRENT_MODEL_VERSION = "bottom-up-1.0.0";
export const MODEL_DECIMAL_PRECISION = 48;
export const MODEL_ROUNDING_MODE = "ROUND_HALF_UP";
export const MODEL_INTERMEDIATE_ROUNDING = "NONE";
export const MODEL_PRESENTATION_ROUNDING = "PRESENTATION_ONLY";
export const MODEL_P80_Z_SCORE = "0.8416";
export const MODEL_MAXIMUM_HOURS_PER_PERSON_DAY = "24";
export const MODEL_MAXIMUM_DAYS_PER_PERSON_MONTH = "31";
